# Generated by Django 6.0.2 on 2026-04-06 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('full_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('minimal_address', models.TextField()),
                ('building_no', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('postal_code', models.PositiveBigIntegerField(validators=[django.core.validators.RegexValidator(message='کد پستی باید 10 رقمی باشد', regex='^\\d{10}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
