# Generated by Django 6.0.2 on 2026-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
