# Generated by Django 6.0.2 on 2026-04-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_banner', '0002_banner_product_to_alter_banner_image_upload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
    ]
