# Generated by Django 5.2.8 on 2026-02-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
        ('app_product', '0014_alter_productspec_key_alter_productspec_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='selected_size',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selected_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='app_product.productcolor'),
            preserve_default=False,
        ),
    ]
