# Generated by Django 6.0.2 on 2026-04-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0003_alter_cartitem_selected_color_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
