# Generated by Django 6.0.2 on 2026-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('error_pay', 'پرداخت نا موافق'), ('paid', 'پرداخت شده'), ('error_ship', 'مشکل در ارسال'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده')], default='pending', max_length=20),
        ),
    ]
