# Generated by Django 6.0.2 on 2026-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
