# Generated by Django 6.0.2 on 2026-04-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_buy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
