# Generated by Django 6.0.2 on 2026-04-23 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_orderitem_price_at_buy'),
        ('app_product', '0016_remove_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_product.productcolor'),
        ),
    ]
