# Generated by Django 5.2.8 on 2026-02-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
