# Generated by Django 5.2.8 on 2026-02-19 05:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0010_remove_product_image_upload_remove_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_shop',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#3b82f6', image_field=None, max_length=25, null=True, samples=None, verbose_name='رنگ محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رنگ'),
        ),
    ]
