# Generated by Django 6.0.2 on 2026-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0014_alter_productspec_key_alter_productspec_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=500, verbose_name='وزن به گرم'),
        ),
    ]
