# Generated by Django 6.0.2 on 2026-04-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0015_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
